remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
gem "github-pages", group: :jekyll_plugins

title: Insect Recognizer
description: Recognize Top 12 Harmful Insects for crop


show_downloads: fakse
google_analytics:
